export const PersonajesArr = [
  {
    id: 1,
    name: 'Joffrey Baratheon',
    typeOfCharacter: 'king',
    yearsOfReign: 1.5,
    age: 16,
    emoji: '👑',
    phrase: 'Vais a morir todos',
  },
  {
    id: 2,
    name: 'Jaime Lannister',
    typeOfCharacter: 'fighter',
    weapon: 'sword',
    skill: 7,
    age: 32,
    emoji: '🗡',
    phrase: 'Soy un loser',
  },
  {
    id: 3,
    name: 'Daenerys Targaryen ',
    typeOfCharacter: 'fighter',
    weapon: 'dragons',
    skill: 9,
    age: 20,
    phrase: 'Soy un loser',
  },
  {
    id: 4,
    name: 'Tyrion Lannister',
    typeOfCharacter: 'adviser',
    adviserOf: 'Daenerys',
    age: 26,
    emoji: '🎓',
    phrase: 'No sé por qué, pero creo que voy a morir pronto',
  },
  {
    id: 5,
    name: 'Bronn Stokeworth',
    typeOfCharacter: 'squire',
    squirerOf: 'Jaime Lannister',
    gradeOfSubmission: '9',
    age: 41,
    emoji: '🛡',
    phrase: 'Soy un loser',
  },
];
